In [10]:
import numpy as np
a=np.array([1,4,5,6])
print(a)

[1 4 5 6]


In [11]:
type(a)

numpy.ndarray

In [12]:
b=np.array([1,5.3,2,6.7])
print(b)

[1.  5.3 2.  6.7]


In [13]:
age=np.array([10,20,13,12,34,56,24,32,43,32])
age=np.sort(age)
print(age)

[10 12 13 20 24 32 32 34 43 56]


In [25]:
d=np.array([[1,2],[1,3],[1,4]])
print("array \n",d)
print("type ",type(d))
print("size ",d.size)
print("size ",d.ndim)
print("shape ",d.shape)
print("datatype ",d.dtype)

array 
 [[1 2]
 [1 3]
 [1 4]]
type  <class 'numpy.ndarray'>
size  6
size  2
shape  (3, 2)
datatype  int32


In [62]:
c=np.arange(1,22,2.5)
print("array is ", c)
print("reshaped array is \n",c.reshape(3,3))#no.of elements in array =produvt of the row*column want to create
print(np.min(c))
print(np.max(c))
print(np.sort(c))
print(np.mean(c))
print(np.median(c))

array is  [ 1.   3.5  6.   8.5 11.  13.5 16.  18.5 21. ]
reshaped array is 
 [[ 1.   3.5  6. ]
 [ 8.5 11.  13.5]
 [16.  18.5 21. ]]
1.0
21.0
[ 1.   3.5  6.   8.5 11.  13.5 16.  18.5 21. ]
11.0
11.0


In [60]:
a1=np.arange(1,10,1).reshape(3,3)
a2=np.arange(10,19,1).reshape(3,3)
print("array 1 is \n",a1)
print("array 2 is \n",a2)
print("addition \n",a1+a2)
print("subtraction \n",a1-a2)
print("multiplication \n",a1@a2)#matric multiplication
print("division \n",a1%a2)

array 1 is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array 2 is 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
addition 
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
subtraction 
 [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
multiplication 
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
division 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
a1=np.arange(1,10,1).reshape(3,3)
print(np.var(a1))
print(np.std(a1))
print(np.linalg.det(a1))
print(np.linalg.eig(a1))
print(np.linalg.eigvals(a1))

6.666666666666667
2.581988897471611
-9.51619735392994e-16
(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


In [75]:
a1=np.arange(1,10,1)
a1=a1[a1>5]
a1

array([6, 7, 8, 9])